
import { Restaurant } from './types';

export const COLORS = {
  HOT_PINK: '#FF00CC',
  PURPLE: '#8A2BE2',
  CYAN: '#00C2FF',
  YELLOW: '#FFD700',
  WHITE: '#FFFFFF',
  BLACK: '#1A1A1A',
  GREY: '#F2F2F2',
};

export const CATEGORIES = [
  { name: 'Fast Food', icon: '🍔' },
  { name: 'Filipino', icon: '🍲' },
  { name: 'Pizza', icon: '🍕' },
  { name: 'Milk Tea', icon: '🧋' },
  { name: 'Coffee', icon: '☕' },
  { name: 'Desserts', icon: '🍰' },
  { name: 'Japanese', icon: '🍱' },
  { name: 'Korean', icon: '🍗' },
  { name: 'Seafood', icon: '🦞' },
  { name: 'Healthy', icon: '🥗' },
  { name: 'Steak', icon: '🥩' },
];

const generateItems = (prefix: string, cuisine: string) => [
  { id: `${prefix}1`, name: `Signature ${cuisine} Plate`, price: 250, description: 'The chef\'s special selection of premium ingredients.', image: `https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=200`, category: 'Best Sellers', isPopular: true },
  { id: `${prefix}2`, name: `Classic ${cuisine} Bowl`, price: 180, description: 'A hearty serving of traditional flavors.', image: `https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=200`, category: 'Main Course' },
  { id: `${prefix}3`, name: `Spicy ${cuisine} Wings`, price: 210, description: 'Coated in our secret spicy glaze.', image: `https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&q=80&w=200`, category: 'Appetizers', isSpicy: true },
  { id: `${prefix}4`, name: `${cuisine} Delight`, price: 120, description: 'A light and refreshing snack.', image: `https://images.unsplash.com/photo-1493770348161-369560ae357d?auto=format&fit=crop&q=80&w=200`, category: 'Snacks' },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Jollibee Iligan',
    rating: 4.8,
    deliveryTime: '20-30 min',
    cuisine: 'Fast Food',
    isPartner: true,
    address: 'Aguinaldo St, Iligan City',
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&q=80&w=600',
    items: [
      { id: 'j1', name: 'Chickenjoy 1pc w/ Spaghetti', price: 135, description: 'Crispy licious chicken served with the legendary sweet-style spaghetti.', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=200', category: 'Best Sellers', isPopular: true },
      { id: 'j2', name: 'Yumburger w/ Fries', price: 95, description: 'Classic beef burger with a side of crispy golden fries.', image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&q=80&w=200', category: 'Burgers' },
      { id: 'j3', name: 'Chocolate Sundae', price: 45, description: 'Creamy vanilla soft serve topped with rich chocolate syrup.', image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&q=80&w=200', category: 'Desserts' },
    ]
  },
  {
    id: '2',
    name: "Tatay's Grill",
    rating: 4.9,
    deliveryTime: '35-50 min',
    cuisine: 'Filipino BBQ',
    isPartner: true,
    address: 'Pala-o, Iligan City',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600',
    items: [
      { id: 't1', name: 'Special Pork BBQ (3pcs)', price: 120, description: 'Marinated in Tatay’s secret sauce and grilled to perfection.', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=200', category: 'Best Sellers', isPopular: true },
      { id: 't2', name: 'Chicken Inasal', price: 165, description: 'Iligan-style grilled chicken with annatto oil and lime.', image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=200', category: 'Main Course' },
      { id: 't4', name: 'Extra Java Rice', price: 25, description: 'Yellow-colored savory rice.', image: 'https://images.unsplash.com/photo-1512058560366-cd2427ff6675?auto=format&fit=crop&q=80&w=200', category: 'Sides' },
    ]
  },
  {
    id: '3',
    name: 'Streetwise Coffee',
    rating: 4.7,
    deliveryTime: '15-25 min',
    cuisine: 'Cafe & Pastries',
    isPartner: false,
    address: 'Tibanga Highway, Iligan City',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=600',
    items: [
      { id: 's1', name: 'Spanish Latte (Iced)', price: 145, description: 'Strong espresso with condensed milk for a sweet kick.', image: 'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?auto=format&fit=crop&q=80&w=200', category: 'Coffee', isPopular: true },
      { id: 's2', name: 'Caramel Macchiato', price: 155, description: 'Layered espresso with vanilla syrup and caramel drizzle.', image: 'https://images.unsplash.com/photo-1485808191679-5f6333c1d181?auto=format&fit=crop&q=80&w=200', category: 'Coffee' },
    ]
  },
  {
    id: '4',
    name: 'Pizza House Iligan',
    rating: 4.6,
    deliveryTime: '40-55 min',
    cuisine: 'Pizza & Pasta',
    isPartner: true,
    address: 'Quezon Ave, Iligan City',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600',
    items: [
      { id: 'p1', name: 'Hawaiian Overload', price: 350, description: 'Loaded with pineapples, ham, and premium cheese.', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=200', category: 'Pizza', isPopular: true },
      { id: 'p3', name: 'Spicy Buffalo Wings', price: 220, description: '6 pieces of wings tossed in extra hot buffalo sauce.', image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&q=80&w=200', category: 'Appetizers', isSpicy: true },
    ]
  },
  {
    id: '5',
    name: 'Sunburst Fried Chicken',
    rating: 4.9,
    deliveryTime: '25-40 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Tibanga, Iligan City',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600',
    items: generateItems('sun', 'Chicken'),
  },
  {
    id: '6',
    name: 'Tokyo Tokyo',
    rating: 4.5,
    deliveryTime: '30-45 min',
    cuisine: 'Japanese',
    isPartner: true,
    address: 'Gaisano Mall, Iligan',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=600',
    items: generateItems('tok', 'Bento'),
  },
  {
    id: '7',
    name: "Cheding's Peanuts",
    rating: 5.0,
    deliveryTime: '15-20 min',
    cuisine: 'Local Delicacy',
    isPartner: true,
    address: 'Saray, Iligan City',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600',
    items: [
      { id: 'ch1', name: 'Classic Salted Peanuts (500g)', price: 180, description: 'Iligan\'s world-famous crunchy peanuts.', image: 'https://images.unsplash.com/photo-1569460275615-7dc3efc173d9?auto=format&fit=crop&q=80&w=200', category: 'Pasalubong', isPopular: true },
      { id: 'ch2', name: 'Sugar Coated Peanuts', price: 195, description: 'Sweet and crunchy treats.', image: 'https://images.unsplash.com/photo-1569460275615-7dc3efc173d9?auto=format&fit=crop&q=80&w=200', category: 'Pasalubong' },
    ],
  },
  {
    id: '8',
    name: "Aruma Coffee",
    rating: 4.8,
    deliveryTime: '20-30 min',
    cuisine: 'Coffee',
    isPartner: true,
    address: 'Quezon Ave, Iligan',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=600',
    items: generateItems('aru', 'Espresso'),
  },
  {
    id: '9',
    name: "Kevlo's Steakhouse",
    rating: 4.7,
    deliveryTime: '45-60 min',
    cuisine: 'Steak',
    isPartner: true,
    address: 'Pala-o, Iligan',
    image: 'https://images.unsplash.com/photo-1546964124-0cce462f38e1?auto=format&fit=crop&q=80&w=600',
    items: generateItems('kev', 'Steak'),
  },
  {
    id: '10',
    name: "Greenery Salads",
    rating: 4.4,
    deliveryTime: '25-35 min',
    cuisine: 'Healthy',
    isPartner: false,
    address: 'Tibanga, Iligan',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    items: generateItems('gre', 'Salad'),
  },
  {
    id: '11',
    name: "Burger King",
    rating: 4.6,
    deliveryTime: '25-35 min',
    cuisine: 'Fast Food',
    isPartner: true,
    address: 'Robinson’s Place Iligan',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600',
    items: generateItems('bk', 'Whopper'),
  },
  {
    id: '12',
    name: "Bonchon Chicken",
    rating: 4.7,
    deliveryTime: '30-40 min',
    cuisine: 'Korean',
    isPartner: true,
    address: 'Robinson’s Place Iligan',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&q=80&w=600',
    items: generateItems('bon', 'Korean Fried Chicken'),
  },
  {
    id: '13',
    name: "Starbucks Iligan",
    rating: 4.8,
    deliveryTime: '20-30 min',
    cuisine: 'Coffee',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=600',
    items: generateItems('sb', 'Frappuccino'),
  },
  {
    id: '14',
    name: "Iligan Night Market Grill",
    rating: 4.9,
    deliveryTime: '40-50 min',
    cuisine: 'Filipino BBQ',
    isPartner: false,
    address: 'Saray Market',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58b3fffc9?auto=format&fit=crop&q=80&w=600',
    items: generateItems('nm', 'Isaw'),
  },
  {
    id: '15',
    name: "The Port Coffee",
    rating: 4.7,
    deliveryTime: '25-35 min',
    cuisine: 'Cafe',
    isPartner: true,
    address: 'Port Area, Iligan',
    image: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&q=80&w=600',
    items: generateItems('tp', 'Brew'),
  },
  {
    id: '16',
    name: "Gloria's Seafood",
    rating: 4.6,
    deliveryTime: '45-60 min',
    cuisine: 'Seafood',
    isPartner: true,
    address: 'Tubod, Iligan',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&q=80&w=600',
    items: generateItems('glo', 'Seafood'),
  },
  {
    id: '17',
    name: "Pancake House",
    rating: 4.5,
    deliveryTime: '30-45 min',
    cuisine: 'Breakfast',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ph', 'Pancake'),
  },
  {
    id: '18',
    name: "Greenwich Pizza",
    rating: 4.4,
    deliveryTime: '35-50 min',
    cuisine: 'Pizza',
    isPartner: true,
    address: 'Quezon Ave.',
    image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600',
    items: generateItems('grw', 'Pizza'),
  },
  {
    id: '19',
    name: "Yellow Cab",
    rating: 4.7,
    deliveryTime: '40-55 min',
    cuisine: 'Pizza',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=600',
    items: generateItems('yc', 'New York Pizza'),
  },
  {
    id: '20',
    name: "Shakey's Pizza",
    rating: 4.6,
    deliveryTime: '40-60 min',
    cuisine: 'Pizza',
    isPartner: true,
    address: 'Gaisano Iligan',
    image: 'https://images.unsplash.com/photo-1593504049359-74330189a345?auto=format&fit=crop&q=80&w=600',
    items: generateItems('sk', 'Thin Crust'),
  },
  {
    id: '21',
    name: "KFC Iligan",
    rating: 4.5,
    deliveryTime: '25-35 min',
    cuisine: 'Fast Food',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?auto=format&fit=crop&q=80&w=600',
    items: generateItems('kfc', 'Bucket Meal'),
  },
  {
    id: '22',
    name: "McDonald's",
    rating: 4.6,
    deliveryTime: '20-30 min',
    cuisine: 'Fast Food',
    isPartner: true,
    address: 'Quezon Ave.',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=600',
    items: generateItems('mc', 'Big Mac'),
  },
  {
    id: '23',
    name: "Mang Inasal",
    rating: 4.8,
    deliveryTime: '30-45 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=600',
    items: generateItems('mi', 'Inasal'),
  },
  {
    id: '24',
    name: "Chowking",
    rating: 4.4,
    deliveryTime: '25-40 min',
    cuisine: 'Chinese',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ck', 'Siomai'),
  },
  {
    id: '25',
    name: "Red Ribbon",
    rating: 4.7,
    deliveryTime: '15-25 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Gaisano Iligan',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    items: generateItems('rr', 'Cake'),
  },
  {
    id: '26',
    name: "Goldilocks",
    rating: 4.6,
    deliveryTime: '15-25 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Quezon Ave.',
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=600',
    items: generateItems('gl', 'Mamon'),
  },
  {
    id: '27',
    name: "Dunkin' Donuts",
    rating: 4.5,
    deliveryTime: '15-20 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=600',
    items: generateItems('dd', 'Donut'),
  },
  {
    id: '28',
    name: "Mister Donut",
    rating: 4.4,
    deliveryTime: '15-20 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Pala-o Market',
    image: 'https://images.unsplash.com/photo-1527515545081-5db817172677?auto=format&fit=crop&q=80&w=600',
    items: generateItems('md', 'Donut'),
  },
  {
    id: '29',
    name: "Krispy Kreme",
    rating: 4.8,
    deliveryTime: '20-30 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=600',
    items: generateItems('kk', 'Glazed'),
  },
  {
    id: '30',
    name: "Chatime",
    rating: 4.7,
    deliveryTime: '20-35 min',
    cuisine: 'Milk Tea',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ct', 'Milk Tea'),
  },
  {
    id: '31',
    name: "CoCo Fresh Tea",
    rating: 4.8,
    deliveryTime: '20-35 min',
    cuisine: 'Milk Tea',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    items: generateItems('cf', 'Panda Milk Tea'),
  },
  {
    id: '32',
    name: "Gong Cha",
    rating: 4.6,
    deliveryTime: '20-35 min',
    cuisine: 'Milk Tea',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    items: generateItems('gc', 'Wintermelon'),
  },
  {
    id: '33',
    name: "Dakasi",
    rating: 4.5,
    deliveryTime: '20-35 min',
    cuisine: 'Milk Tea',
    isPartner: true,
    address: 'Quezon Ave.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    items: generateItems('dk', 'Oreo Milk Tea'),
  },
  {
    id: '34',
    name: "Infinitea",
    rating: 4.3,
    deliveryTime: '20-35 min',
    cuisine: 'Milk Tea',
    isPartner: true,
    address: 'Pala-o',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    items: generateItems('it', 'Classic Milk Tea'),
  },
  {
    id: '35',
    name: "Bo's Coffee",
    rating: 4.6,
    deliveryTime: '25-35 min',
    cuisine: 'Coffee',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=600',
    items: generateItems('bc', 'Barako'),
  },
  {
    id: '36',
    name: "Coffee Bean & Tea Leaf",
    rating: 4.7,
    deliveryTime: '25-35 min',
    cuisine: 'Coffee',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=600',
    items: generateItems('cbtl', 'Ice Blended'),
  },
  {
    id: '37',
    name: "Seattle's Best",
    rating: 4.5,
    deliveryTime: '25-35 min',
    cuisine: 'Coffee',
    isPartner: true,
    address: 'Gaisano Iligan',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=600',
    items: generateItems('sbc', 'Javachip'),
  },
  {
    id: '38',
    name: "Army Navy",
    rating: 4.7,
    deliveryTime: '35-50 min',
    cuisine: 'Burgers',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=600',
    items: generateItems('an', 'Bully Burger'),
  },
  {
    id: '39',
    name: "Zark's Burgers",
    rating: 4.8,
    deliveryTime: '35-50 min',
    cuisine: 'Burgers',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600',
    items: generateItems('zb', 'Jawbreaker'),
  },
  {
    id: '40',
    name: "Brothers Burger",
    rating: 4.6,
    deliveryTime: '35-50 min',
    cuisine: 'Burgers',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=600',
    items: generateItems('bb', 'Brothers Burger'),
  },
  {
    id: '41',
    name: "Kenny Rogers Roasters",
    rating: 4.7,
    deliveryTime: '40-55 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Quezon Ave.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600',
    items: generateItems('krr', 'Roasted Chicken'),
  },
  {
    id: '42',
    name: "Max's Restaurant",
    rating: 4.8,
    deliveryTime: '40-60 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600',
    items: generateItems('mr', 'Whole Chicken'),
  },
  {
    id: '43',
    name: "Aristocrat",
    rating: 4.6,
    deliveryTime: '40-60 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Tibanga',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ari', 'BBQ Chicken'),
  },
  {
    id: '44',
    name: "Conti's Bakeshop",
    rating: 4.9,
    deliveryTime: '30-45 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    items: generateItems('con', 'Mango Bravo'),
  },
  {
    id: '45',
    name: "Mary Grace",
    rating: 4.8,
    deliveryTime: '30-45 min',
    cuisine: 'Desserts',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=600',
    items: generateItems('mg', 'Ensaymada'),
  },
  {
    id: '46',
    name: "Pepper Lunch",
    rating: 4.7,
    deliveryTime: '30-45 min',
    cuisine: 'Japanese',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1546964124-0cce462f38e1?auto=format&fit=crop&q=80&w=600',
    items: generateItems('pl', 'Beef Pepper Rice'),
  },
  {
    id: '47',
    name: "Sizzlin' Steak",
    rating: 4.4,
    deliveryTime: '35-50 min',
    cuisine: 'Steak',
    isPartner: true,
    address: 'Gaisano Iligan',
    image: 'https://images.unsplash.com/photo-1546964124-0cce462f38e1?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ss', 'Sizzling Steak'),
  },
  {
    id: '48',
    name: "Dads World Buffet",
    rating: 4.8,
    deliveryTime: '50-70 min',
    cuisine: 'Filipino',
    isPartner: true,
    address: 'Aguinaldo St.',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58b3fffc9?auto=format&fit=crop&q=80&w=600',
    items: generateItems('dwb', 'Buffet Box'),
  },
  {
    id: '49',
    name: "Vikings",
    rating: 4.9,
    deliveryTime: '50-70 min',
    cuisine: 'International',
    isPartner: true,
    address: 'Tibanga Highway',
    image: 'https://images.unsplash.com/photo-1551248429-40975aa4de74?auto=format&fit=crop&q=80&w=600',
    items: generateItems('vik', 'Gourmet Feast'),
  },
  {
    id: '50',
    name: "Sambokojin",
    rating: 4.7,
    deliveryTime: '50-70 min',
    cuisine: 'Japanese',
    isPartner: true,
    address: 'Robinson’s Iligan',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=600',
    items: generateItems('sam', 'Yakiniku Set'),
  },
  {
    id: '51',
    name: "Sambo Sam",
    rating: 4.5,
    deliveryTime: '30-45 min',
    cuisine: 'Korean',
    isPartner: true,
    address: 'Pala-o',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&q=80&w=600',
    items: generateItems('ssm', 'Samgyupsal'),
  }
];
